### ISSUE TITLE
safer docmd_i_pct_yr()

### ISSUE THREAD

**Issue by achan001** [thomasokken/plus42#1]
Current implementation solve npv = 0, for rate x (**tvm_eq(), in core_commands8.cc**)
If rate x overshoot, it is possible npv' goes small, possibly even 0.
This may cause Newton's method to go unstable.

It may be better to solve npmt = 0, for rate x

Example, from "Financial Analysis and Business Decisions on the pocket calculator", p65
```
XCas> npmt := PMT + ((PV+FV)/expm1(N*log1p(x))+PV)*x
XCas> npv := PV + PMT*(-expm1(-N*log1p(x))/x) + FV*exp(-N*log1p(x))

XCas> PMT, PV, FV, N := -742.26, 25e3, 0, 40
XCas> limit(npmt', x=inf)  ----> 25000
XCas> limit(npv' , x=inf)  ----> 0
```

Solving npmt=0 is very stable, even with bad rate guess, say 1 BILLION PERCENT
```
XCas> (x-npmt/npmt')(x=1.0e7) ----> 0.029690399766
XCas> (x-npmt/npmt')(x=ans()) ----> 0.010545795145
XCas> (x-npmt/npmt')(x=ans()) ----> 0.00868643617136
XCas> (x-npmt/npmt')(x=ans()) ----> 0.00866682879974
XCas> (x-npmt/npmt')(x=ans()) ----> 0.00866682660679
```

Bonus, with same rate guess, npmt version converge faster than npv
```
XCas> (x-npmt/npmt')(x=.0001) ----> 0.00914018365257
XCas> (x-npmt/npmt')(x=ans()) ----> 0.00866809621578
XCas> (x-npmt/npmt')(x=ans()) ----> 0.00866682661598

XCas> (x-npv/npv')(x=.0001) ------> 0.00772765748743
XCas> (x-npv/npv')(x=ans()) ------> 0.00865500236498
XCas> (x-npv/npv')(x=ans()) ------> 0.00866682472201
```

**Comment by thomasokken** [comment]
I implemented your proposal: 94849493bc59b307c18c4dc88b9ead879e6e253b
Could you verify?

**Comment by achan001** [comment]
Looks OK

**Comment by thomasokken** [comment]
Great, thanks!
