### ISSUE TITLE
plus42/gtk's keymap

### ISSUE THREAD

**Issue by sonhoan** [thomasokken/plus42#3]
Buttons of the plus42/gtk's third row from the top, LOG LN XEQ raw, do not keep 'one push shift' by 'keyboard short-cut,' but top f keys row can do e^x, GTO, with one push shift as free42, instead.

**Comment by thomasokken** [comment]
I'm afraid I don't understand. Could you elaborate?

**Comment by thomasokken** [comment]
Oh, no, wait, I think I get it. Shift+V is Y^X, but Shift, and then V as a separate keystroke, is 1/X, because the Shift state is not taken into account when resolving the key mapping.
That's not good, and should be fixed. Is that what you were referring to?

**Comment by thomasokken** [comment]
a1093a69ee7a1916079426198159b7d263bf873f
